[package]
name = "sl1-iced-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["tokio"] }
serde = "1.0.219"
serde_json = "1.0.140"
# tokio = { version = "1.44.1", features = ["full"] }
tracing-subscriber = "0.3.19"
